title: Skyly
description: >-
  Simplement un serveur mini-jeux incroyable !
url: https://skylymc.github.io/skyly.github.io/
server_address: skyly.fr

google_analytics: G-ZTJL2E4CJW

sass:
  sass_dir: assets/css
  style: compressed

defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: assets/img/image-slider
    values:
      image_slider: true

include: [
  '_pages'
]

exclude: [
  'README.md',
  'LICENSE.md'
]

plugins:
  - jekyll-redirect-from
